name: Build and publish a anniv-check
on:
  release:
    types: [ published ]
  push:
    branches:
      - master

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: projectanni/anniv-check
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: meta/cmd/Dockerfile
        env:
          DOCKER_BUILDKIT: 1

